main = "./dist/v2-aes-shop/server/main.js"

name = "mnmmas-shop-ssr"
account_id = "0a0f186a4d7d68e253499cbd0c13d913"
workers_dev = true
compatibility_date = "2024-08-20"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./dist/v2-aes-shop/browser"


