name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ejecutar en push a la rama main
    tags:
      - '*'  # También ejecuta cuando se hace un push de un tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Extraer el nombre del repositorio y convertirlo a minúsculas
    - name: Extract repository name and convert to lowercase
      id: repo
      run: echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY##*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # 3. Login en GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    # 4. Construir y empujar la imagen
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.ref_name }}
